### ISSUE TITLE
Request: Sankey diagram

### ISSUE THREAD

**Issue by jspronk** [dartungar/obsidian-mermaid#47]
A few months ago the ability to create Sankey diagrams was added to Mermaid.  It would change my life if I could create these in Obsidian. 

[Mermaid: Sankey diagram](https://mermaid.js.org/syntax/sankey.html)

**Comment by dartungar** [comment]
@jspronk you can! This plugin does not affect rendering Mermaid at any way, it just provides a convenient toolbar :)

There are some problems with rendering Sankey (it's still beta) in the toolbar, so I won't be adding it to the toolbar until these are fixes.

**Comment by jspronk** [comment]
Oh nice!

Do you happen to have a working example you could share? I'm playing with the syntax and just cant seem to get any diagram to rendder...instead I get the following:

```
Error parsing Mermaid diagram!

No diagram type detected matching given configuration for text: sankey
```

**Comment by PDWest** [comment]
This issue is strangely timely: From the beginning of the year through last Friday, Jan 12, 2024, I had been using Obsidian to develop and render mermaid Sanke diagrams to great effect.  Today, I tried to view some of my erstwhile beautiful diagrams but found them to be missing the colorful connection flows!  Even the simple example from the mermaid docs at https://mermaid.js.org/syntax/sankey.html :

```
sankey-beta
%% source,target,value
Electricity grid,Over generation / exports,104.453
Electricity grid,Heating and cooling - homes,113.726
Electricity grid,H2 conversion,27.14
```
renders as:
![image](https://github.com/dartungar/obsidian-mermaid/assets/8768844/378b6f01-f986-4c1f-9c21-969ec8730234)

instead of (as it did last week):
![image](https://github.com/dartungar/obsidian-mermaid/assets/8768844/4597d3a8-2702-49cd-aba1-6bf99ec19220)

I've got no clue what might be wrong and I don't understand what resource chain is used by Obsidian to get the ultimate image.  I can say that it's not a wholesale mermaid issue as all of the Gantt and  Flowcharts that I viewed still look fine.

-Phil

**Comment by jspronk** [comment]
I am having the same issue.

**Comment by dartungar** [comment]
@jspronk @PDWest examples from https://mermaid.js.org/syntax/sankey.html worked fine for me, however right now there is indeed some trouble with Obsidian's rendering of Mermaid... Nothing I can do about that, your best bet is creating bug on official forums :(
