### ISSUE TITLE
[BUG] Mermaid code fence not inserted with chosen element

### ISSUE THREAD

**Issue by zanodor** [dartungar/obsidian-mermaid#50]
I inspected the code and I've seen the part -- that doesn't get called?

I had to apply a hack (I'm no dev) for the time being (as other approaches didn't yield the desired result):
````
  getSampleDiagram(category) {
    return this.wrapForPastingIntoEditor(this.wrapWithMermaidBlock(sampleDiagrams[category]));
  }
  wrapForPastingIntoEditor(text) {
    return `\`\`\`mermaid
${text}
\`\`\``;
  }
  wrapWithMermaidBlock(text) {
    return `\`\`\`mermaid
${text}
\`\`\``;
  }
````

**Comment by dartungar** [comment]
@zanodor This is intended: code fence is inserted only when using "Insert code block" button:
![image](https://github.com/dartungar/obsidian-mermaid/assets/36126057/064836b2-f1b4-4441-9054-41b8e60c713a)

Elements are inserted without the fence since there might be more than 1 element inside 1 fence. Cheers!
